using System;
using System.Collections.Generic;

namespace DurandalAuth.Domain.Models
{
    public partial class activity_log_hactivity_log
    {
        public string ac_id { get; set; }
        public string act_quest { get; set; }
        public string action_title { get; set; }
        public int activity_log_id { get; set; }
        public string activity_type { get; set; }
        public string approved_by { get; set; }
        public string assessed_by { get; set; }
        public string assigned_to { get; set; }
        public short autocreate_wr { get; set; }
        public string bl_id { get; set; }
        public string capital_program { get; set; }
        public string cf_id { get; set; }
        public string comments { get; set; }
        public string completed_by { get; set; }
        public short cond_priority { get; set; }
        public short cond_value { get; set; }
        public Nullable<int> copied_from { get; set; }
        public decimal cost_act_cap { get; set; }
        public decimal cost_actual { get; set; }
        public string cost_cat_id { get; set; }
        public decimal cost_est_cap { get; set; }
        public decimal cost_est_design_cap { get; set; }
        public decimal cost_est_design_exp { get; set; }
        public decimal cost_estimated { get; set; }
        public decimal cost_to_replace { get; set; }
        public string created_by { get; set; }
        public string csi_id { get; set; }
        public Nullable<System.DateTime> date_approved { get; set; }
        public Nullable<System.DateTime> date_assessed { get; set; }
        public Nullable<System.DateTime> date_closed { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public Nullable<System.DateTime> date_escalation_completion { get; set; }
        public Nullable<System.DateTime> date_escalation_response { get; set; }
        public Nullable<System.DateTime> date_installed { get; set; }
        public Nullable<System.DateTime> date_issued { get; set; }
        public Nullable<System.DateTime> date_planned_end { get; set; }
        public Nullable<System.DateTime> date_planned_for { get; set; }
        public System.DateTime date_requested { get; set; }
        public Nullable<System.DateTime> date_required { get; set; }
        public Nullable<System.DateTime> date_review { get; set; }
        public Nullable<System.DateTime> date_scheduled { get; set; }
        public Nullable<System.DateTime> date_scheduled_end { get; set; }
        public Nullable<System.DateTime> date_started { get; set; }
        public Nullable<System.DateTime> date_verified { get; set; }
        public string description { get; set; }
        public string dispatcher { get; set; }
        public string dp_id { get; set; }
        public int duration { get; set; }
        public short duration_act { get; set; }
        public short duration_est_baseline { get; set; }
        public string dv_id { get; set; }
        public string dwgname { get; set; }
        public string ehandle { get; set; }
        public string eq_id { get; set; }
        public short escalated_completion { get; set; }
        public short escalated_response { get; set; }
        public string fl_id { get; set; }
        public string fund_id { get; set; }
        public int hours_actual { get; set; }
        public int hours_est_baseline { get; set; }
        public int hours_est_design { get; set; }
        public string location { get; set; }
        public string ls_id { get; set; }
        public string manager { get; set; }
        public Nullable<int> mo_id { get; set; }
        public string op_id { get; set; }
        public string option1 { get; set; }
        public string option2 { get; set; }
        public string owner_type { get; set; }
        public string parcel_id { get; set; }
        public short pct_complete { get; set; }
        public string phone_requestor { get; set; }
        public Nullable<int> po_id { get; set; }
        public string pr_id { get; set; }
        public string predecessors { get; set; }
        public Nullable<short> priority { get; set; }
        public string prob_type { get; set; }
        public string proj_phase { get; set; }
        public string project_id { get; set; }
        public short qty_life_expct { get; set; }
        public short rec_action { get; set; }
        public Nullable<int> regcomp_id { get; set; }
        public string requestor { get; set; }
        public string requestor_type { get; set; }
        public string resp_id { get; set; }
        public string rm_id { get; set; }
        public short satisfaction { get; set; }
        public string satisfaction_notes { get; set; }
        public string site_id { get; set; }
        public short start_offset { get; set; }
        public string status { get; set; }
        public string step_status { get; set; }
        public string supervisor { get; set; }
        public short sust_priority { get; set; }
        public Nullable<System.DateTime> time_escalation_completion { get; set; }
        public Nullable<System.DateTime> time_escalation_response { get; set; }
        public Nullable<System.DateTime> time_requested { get; set; }
        public Nullable<System.DateTime> time_required { get; set; }
        public string tr_id { get; set; }
        public string verified_by { get; set; }
        public string vn_id { get; set; }
        public string wbs_id { get; set; }
        public Nullable<int> wo_id { get; set; }
        public string work_pkg_id { get; set; }
        public string work_team_id { get; set; }
        public Nullable<int> wr_id { get; set; }
        public string recurring_rule { get; set; }
        public Nullable<int> assessment_id { get; set; }
        public string pmp_id { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lon { get; set; }
        public Nullable<int> geo_objectid { get; set; }
    }
}
