using System;
using System.Collections.Generic;

namespace DurandalAuth.Domain.Models
{
    public partial class afm_userprocs
    {
        public short autogenerated { get; set; }
        public Nullable<int> internal_use1 { get; set; }
        public string transfer_status { get; set; }
        public string user_name { get; set; }
        public string activity_id { get; set; }
        public string process_id { get; set; }
        public virtual afm_activities afm_activities { get; set; }
        public virtual afm_processes afm_processes { get; set; }
        public virtual afm_users afm_users { get; set; }
    }
}
